name: ClangFormat Linter

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  clangformat:
    runs-on: ubuntu-latest
    name: ClangFormat

    steps:
      - name: Clone Repository (for push events)
        if: ${{ github.event_name == 'push' }}
        # regular checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clone Repository (for PR events)
        if: ${{ github.event_name == 'pull_request' }}
        # PR checkout
        uses: actions/checkout@v3
        with:
          # checkout the repository the branch is coming from
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          # prevent checkout in detached head state
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: recursive

      - name: Run ClangFormat
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: 'include test experiments'
          extensions: 'hpp,cpp'
          clangFormatVersion: 16
          inplace: True

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'include test experiments'
          commit: '--signoff'
          message: ':art: ClangFormat changes'
          author_name: ClangFormat
          author_email: ClangFormat@users.noreply.github.com
