name: ðŸ â€¢ Docstring Generator

on:
  push:
    paths:
      - "**/*.hpp"
      - ".github/workflows/pyfiction-docstring-generator.yml"
  workflow_dispatch:

jobs:
  get_docstrings:
    name: ðŸ Auto-generate docstrings for pyfiction from C++ code
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14.x"
          cache: "pip"

      - name: Install pybind11_mkdoc and clang
        working-directory: ${{ github.workspace }}
        run: pip install pybind11_mkdoc clang==15.0.7

      - name: Create docstrings file
        working-directory: ${{ github.workspace }}
        run: touch ${{ github.workspace }}/pybind11_mkdoc_docstrings.hpp

      - name: Run pybind11_mkdoc
        working-directory: ${{ github.workspace }}
        run: >
          python3
          -m pybind11_mkdoc
          -o ${{ github.workspace }}/bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
          -D FICTION_Z3_SOLVER
          -D FICTION_ALGLIB_ENABLED
          `find ${{ github.workspace }}/include/fiction -name "*.hpp" -print`

      - name: Upload docstrings as an artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          path: ${{ github.workspace }}/bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
          overwrite: true

      - name: Commit docstrings
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          add: "bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp"
          commit: "--signoff"
          message: ":memo: Update pyfiction docstrings"
          author_name: GitHub Actions
          author_email: actions@github.com
