name: ðŸªŸ â€¢ CI

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.hpp"
      - "**/*.cpp"
      - "**/*.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/windows.yml"
      - "!bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.hpp"
      - "**/*.cpp"
      - "**/*.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/windows.yml"
      - "!bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh # use pwsh as directory handling does not seem to work with bash

env:
  Z3_VERSION: 4.13.4

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [windows-2022, windows-2025]
        toolset: [v143, ClangCL]
        include:
          - toolset: v143
            cxx_compiler: cl
            c_compiler: cl
          - toolset: ClangCL
            cxx_compiler: clang-cl
            c_compiler: clang-cl

    name: ðŸªŸ ${{matrix.os}} with ${{matrix.toolset}} toolset
    runs-on: ${{matrix.os}}

    steps:
      - name: Clone Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14.x"

      - name: Set up MSVC development environment
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2
        with:
          key: "${{matrix.os}}-${{matrix.toolset}}"
          variant: ccache
          save: true
          max-size: 10G

      - name: Setup Z3 Solver
        id: z3
        uses: cda-tum/setup-z3@8156b32632230f11cf9c5a50becb33d73e2fb4e5 # v1.7.1
        with:
          version: ${{env.Z3_VERSION}}

      # Build and test pipeline for Debug mode

      - name: Configure CMake (Debug)
        run: >
          cmake -S ${{github.workspace}} -B ${{github.workspace}}/build_debug -G Ninja
          -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}}
          -DCMAKE_C_COMPILER=${{matrix.c_compiler}}
          -DCMAKE_BUILD_TYPE=Debug
          -DFICTION_CLI=ON
          -DFICTION_TEST=ON
          -DFICTION_BENCHMARK=OFF
          -DFICTION_EXPERIMENTS=ON
          -DFICTION_Z3=ON
          -DFICTION_ALGLIB=ON
          -DFICTION_WARNINGS_AS_ERRORS=OFF
          -DMOCKTURTLE_EXAMPLES=OFF

      - name: Build (Debug)
        run: cmake --build ${{github.workspace}}/build_debug --config Debug --parallel 4

      - name: Test (Debug)
        run: ctest --test-dir ${{github.workspace}}/build_debug -C Debug --verbose --output-on-failure --repeat until-pass:3 --parallel 4

      # Build and test pipeline for Release mode

      - name: Configure CMake (Release)
        run: >
          cmake -S ${{github.workspace}} -B ${{github.workspace}}/build_release -G Ninja
          -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}}
          -DCMAKE_C_COMPILER=${{matrix.c_compiler}}
          -DCMAKE_BUILD_TYPE=Release
          -DFICTION_CLI=ON
          -DFICTION_TEST=ON
          -DFICTION_BENCHMARK=OFF
          -DFICTION_EXPERIMENTS=ON
          -DFICTION_Z3=ON
          -DFICTION_ALGLIB=ON
          -DFICTION_WARNINGS_AS_ERRORS=OFF
          -DMOCKTURTLE_EXAMPLES=OFF

      - name: Build (Release)
        run: cmake --build ${{github.workspace}}/build_release --config Release --parallel 4

      - name: Test (Release)
        run: ctest --test-dir ${{github.workspace}}/build_release -C Release --verbose --output-on-failure --repeat until-pass:3 --parallel 4
